"""
API Bridge Builder
Autonomous API connection generation with NL parsing, testing, and Ralph loop.
"""

from __future__ import annotations

import json
import sqlite3
import hashlib
from typing import Optional

import anthropic
import httpx
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------

class MappingIntent(BaseModel):
    source_system: str = Field(..., description="Source API or system name")
    target_system: str = Field(..., description="Target API or system name")
    data_fields: list[str] = Field(default_factory=list, description="Fields to map")
    protocol: str = Field(default="REST", description="Protocol: REST, GraphQL, SOAP")


class BridgeResult(BaseModel):
    success: bool
    mapping_applied: dict[str, str] = Field(default_factory=dict)
    test_passed: bool = False
    notes: str = ""


# ---------------------------------------------------------------------------
# NLParser
# ---------------------------------------------------------------------------

class NLParser:
    """Converts plain language descriptions into structured MappingIntent objects."""

    def __init__(self, client: Optional[anthropic.Anthropic] = None) -> None:
        self._client = client or anthropic.Anthropic()

    def parse(self, description: str) -> MappingIntent:
        """Parse a plain language description into a MappingIntent."""
        message = self._client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=512,
            messages=[{
                "role": "user",
                "content": (
                    f"Extract API bridge intent from this description and return ONLY valid JSON "
                    f"with keys: source_system, target_system, data_fields (list), protocol.\n\n"
                    f"Description: {description}"
                )
            }]
        )
        raw = message.content[0].text.strip()
        # Strip markdown code fences if present
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        data = json.loads(raw.strip())
        return MappingIntent(**data)


# ---------------------------------------------------------------------------
# BridgeBuilder
# ---------------------------------------------------------------------------

class BridgeBuilder:
    """Autonomously generates API connection mappings based on structured intents."""

    def __init__(self, client: Optional[anthropic.Anthropic] = None) -> None:
        self._client = client or anthropic.Anthropic()

    def build(self, intent: MappingIntent) -> BridgeResult:
        """Generate a field mapping for the given intent."""
        message = self._client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=512,
            messages=[{
                "role": "user",
                "content": (
                    f"Generate a JSON field mapping (source_field -> target_field) for bridging "
                    f"{intent.source_system} to {intent.target_system} via {intent.protocol}. "
                    f"Fields to map: {intent.data_fields}. "
                    f"Return ONLY a flat JSON object like {{\"source_field\": \"target_field\"}}."
                )
            }]
        )
        raw = message.content[0].text.strip()
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        mapping = json.loads(raw.strip())
        return BridgeResult(success=True, mapping_applied=mapping, notes="Mapping generated by AI")


# ---------------------------------------------------------------------------
# ConnectionTester
# ---------------------------------------------------------------------------

class ConnectionTester:
    """Validates that the mapping is structurally sound (live test with mock endpoints)."""

    def __init__(self, http_client: Optional[httpx.Client] = None) -> None:
        self._client = http_client or httpx.Client(timeout=5.0)

    def test(self, result: BridgeResult) -> bool:
        """Validate the bridge result has a non-empty mapping."""
        if not result.success or not result.mapping_applied:
            return False
        # Structural validation: all keys and values must be non-empty strings
        return all(
            isinstance(k, str) and isinstance(v, str) and k.strip() and v.strip()
            for k, v in result.mapping_applied.items()
        )


# ---------------------------------------------------------------------------
# KnowledgeBase
# ---------------------------------------------------------------------------

class KnowledgeBase:
    """SQLite-backed store that learns from every API bridge run."""

    def __init__(self, db_path: str = "knowledge_base.db") -> None:
        self._db_path = db_path
        self._initialize_schema()

    def _initialize_schema(self) -> None:
        with sqlite3.connect(self._db_path) as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS bridges (
                    intent_key TEXT PRIMARY KEY,
                    source_system TEXT,
                    target_system TEXT,
                    protocol TEXT,
                    mapping JSON,
                    test_passed INTEGER,
                    notes TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """)

    def _intent_to_key(self, intent: MappingIntent) -> str:
        raw = f"{intent.source_system}|{intent.target_system}|{intent.protocol}|{sorted(intent.data_fields)}"
        return hashlib.sha256(raw.encode()).hexdigest()[:16]

    def store(self, intent: MappingIntent, result: BridgeResult) -> None:
        with sqlite3.connect(self._db_path) as conn:
            conn.execute("""
                INSERT OR REPLACE INTO bridges
                    (intent_key, source_system, target_system, protocol, mapping, test_passed, notes)
                VALUES (?, ?, ?, ?, ?, ?, ?)
            """, (
                self._intent_to_key(intent),
                intent.source_system, intent.target_system, intent.protocol,
                json.dumps(result.mapping_applied),
                int(result.test_passed), result.notes
            ))

    def lookup(self, intent: MappingIntent) -> Optional[BridgeResult]:
        with sqlite3.connect(self._db_path) as conn:
            row = conn.execute(
                "SELECT mapping, test_passed, notes FROM bridges WHERE intent_key = ?",
                (self._intent_to_key(intent),)
            ).fetchone()
        if not row:
            return None
        return BridgeResult(
            success=True,
            mapping_applied=json.loads(row[0]),
            test_passed=bool(row[1]),
            notes=f"[from cache] {row[2]}"
        )


# ---------------------------------------------------------------------------
# RalphLoop
# ---------------------------------------------------------------------------

class RalphLoop:
    """Fully autonomous bridge orchestration: parse -> lookup -> build -> test -> refine -> store."""

    def __init__(
        self,
        parser: Optional[NLParser] = None,
        builder: Optional[BridgeBuilder] = None,
        tester: Optional[ConnectionTester] = None,
        knowledge_base: Optional[KnowledgeBase] = None,
        anthropic_client: Optional[anthropic.Anthropic] = None,
    ) -> None:
        client = anthropic_client or anthropic.Anthropic()
        self._parser = parser or NLParser(client)
        self._builder = builder or BridgeBuilder(client)
        self._tester = tester or ConnectionTester()
        self._kb = knowledge_base or KnowledgeBase()

    def _refine_with_feedback(
        self,
        intent: MappingIntent,
        result: BridgeResult,
        previous_result: Optional[BridgeResult],
    ) -> BridgeResult:
        """Merge prior knowledge into current result if previous was better."""
        if previous_result and previous_result.test_passed and not result.test_passed:
            return BridgeResult(
                success=True,
                mapping_applied=previous_result.mapping_applied,
                test_passed=True,
                notes="Refined using prior successful mapping"
            )
        return result

    def run(self, description: str) -> BridgeResult:
        """Execute the full autonomous bridge-building loop."""
        print(f"Parsing: {description}")
        intent = self._parser.parse(description)
        print(f"Intent: {intent.source_system} -> {intent.target_system} ({intent.protocol})")

        prior = self._kb.lookup(intent)
        if prior:
            print(f"Found cached result — skipping rebuild")
            return prior

        result = self._builder.build(intent)
        result.test_passed = self._tester.test(result)
        result = self._refine_with_feedback(intent, result, prior)
        self._kb.store(intent, result)

        print(f"Mapping: {result.mapping_applied}")
        print(f"Test passed: {result.test_passed}")
        return result


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    """Entry point for the API Bridge Builder."""
    loop = RalphLoop()
    result = loop.run(
        "Connect our Salesforce CRM to our SAP ERP system via REST. "
        "Map customer_id, full_name, email, and invoice_total."
    )
    print(f"\nResult: {'Success' if result.success else 'Failed'}")
    print(f"Notes: {result.notes}")


if __name__ == "__main__":
    main()
